---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/karatahta.ethosoft.org/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -f dist/index.html dist/.htaccess dist/logo.png "$DEPLOYPATH"
    - /bin/cp -R -f dist/assets "$DEPLOYPATH"
    - /bin/chmod 755 "$DEPLOYPATH"
    - /bin/chmod 644 "$DEPLOYPATH/index.html" "$DEPLOYPATH/.htaccess" "$DEPLOYPATH/logo.png"
    - /usr/bin/find "$DEPLOYPATH/assets" -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH/assets" -type f -exec /bin/chmod 644 {} \;
