---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ethosoft/karatahta.ethosoft.org/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -R -f dist/. "$DEPLOYPATH"
    - /bin/chmod 755 "$DEPLOYPATH"
    - /usr/bin/find "$DEPLOYPATH" -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -type f -exec /bin/chmod 644 {} \;
