---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ethosoft/karatahta.ethosoft.org/
    - npm ci --include=dev
    - npm run build
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -a dist/. "$DEPLOYPATH"
